[theme]
# Яскравий та енергійний оранжевий, як смуги на боці машини.
primaryColor="#FF8C00"

# Глибокий, темний сірий (Gunmetal), що імітує колір кузова.
backgroundColor="#36454F"

# Майже чорний колір для бічної панелі, що нагадує про решітку радіатора та затемнені вікна.
secondaryBackgroundColor="#2C3539"

# Дуже світло-сірий (майже білий) для тексту, щоб забезпечити чудовий контраст і читабельність.
textColor="#EAEAEA"